# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-27 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('unit', models.CharField(choices=[('Hour', 'hour'), ('Day', 'day'), ('Week', 'week'), ('Month', 'month')], max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTimesheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('source', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_format', models.CharField(choices=[('dd/mm/yyyy', '%d/%m/%Y'), ('mm/dd/yyyy', '%m/%d/%Y')], max_length=255)),
                ('country', models.CharField(choices=[('Jamaica', 'JA'), ('Canada', 'CA'), ('USA', 'USA')], max_length=255)),
                ('pay_period', models.CharField(choices=[('Bi-weekly', 'bi-weekly'), ('Monthly', 'monthly')], max_length=255)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='payroll.Partner')),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='default_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='payroll.PartnerProfile'),
        ),
        migrations.AddField(
            model_name='employeetimesheet',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='payroll.Partner'),
        ),
        migrations.AddField(
            model_name='employeetimesheet',
            name='partner_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='payroll.PartnerProfile'),
        ),
        migrations.AddField(
            model_name='employeetime',
            name='timesheet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_time_records', to='payroll.EmployeeTimesheet'),
        ),
        migrations.AddField(
            model_name='employeegroup',
            name='partner_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_groups', to='payroll.PartnerProfile'),
        ),
        migrations.AlterUniqueTogether(
            name='employeetimesheet',
            unique_together=set([('partner', 'key')]),
        ),
        migrations.AlterUniqueTogether(
            name='employeegroup',
            unique_together=set([('name', 'partner_profile')]),
        ),
    ]
