# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetime',
            name='employee_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='payroll.EmployeeGroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeetime',
            name='employee_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
