# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_auto_20180528_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetime',
            name='employee_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_time_records', to='payroll.EmployeeGroup'),
        ),
    ]
